### ISSUE TITLE
404 from npmjs.org on install

### ISSUE THREAD

**Issue by spinlock99** [amiel/ember-data-url-templates#12]
Hi all,

When I try to install the addon, I get the following error:

    $ember install ember-data-url-tempates
    version: 1.13.14
    Registry returned 404 for GET on https://registry.npmjs.org/ember-data-url-tempates
    Error: Registry returned 404 for GET on https://registry.npmjs.org/ember-data-url-tempates

**Comment by amiel** [comment]
It looks like you have a typo in your install command.

`ember install ember-data-url-tempates` is missing an `l`, it should be `ember install ember-data-url-templates`

I hope this helps :)

**Comment by spinlock99** [comment]
wow.

that was dumb.


thanks so much for your help.
