### ISSUE TITLE
IDs are double URI-encoded

### ISSUE THREAD

**Issue by dfreeman** [amiel/ember-data-url-templates#13]
It looks as though the `id` segment provided out of the box gets escaped both [in the mixin](https://github.com/amiel/ember-data-url-templates/blob/master/addon/mixins/url-templates.js#L54) and again in the `uri-templates` library itself.

[This twiddle](https://ember-twiddle.com/98db5b99cb47b52a5560?openFiles=application.controller.js%2Capplication.template.hbs) demonstrates the issue – you can see the space in the ID gets double encoded into `%2520`.

Should the call to `sanitize` just be taken out of the default `id` segment?

**Comment by amiel** [comment]
Yes! I'm glad you noticed.

I'll happily accept a pull-request if you get to this before I do.

**Comment by dfreeman** [comment]
Happy to – just wanted to make sure I wasn't missing some subtle reason that was there :)

**Comment by amiel** [comment]
It was there because the original ember-data code had the sanitization (it was cargo-culted).
