### ISSUE TITLE
Example of Custom URL for Nested Resources

### ISSUE THREAD

**Issue by borwahs** [amiel/ember-data-url-templates#15]
I currently have the following URL I am trying to get all photos belong to a user:

`/users/:user_id/photos`

I see in the wiki that it is possible to use URL Segments for `createRecordUrlTemplate` using snapshots to get the ID. However, what is the best way to handle building the path for `findAllUrlTemplate` to get the ID for the `parent` aka `users`?

In the URL Segments, the snapshot will be null for `findAll` and `query`.

**Comment by borwahs** [comment]
@amiel, this is very helpful! Both options are useful for me as the first one works with my session store but I also have a couple nested routes that aren't tied to the any session data.

A couple follow ups out of curiosity.

1. I found this shortly before I saw your response - http://blog.ksol.fr/ember-data-working-with-nested-api-resources/. I like the idea of injecting the context via a service. Any downsides you see to that?
2. I implemented your solution with query for a nested route that doesn't use any session data.

    ```javascript
    // route
    export default Ember.Route.extend({
      model(params) {
        return this.store.query('location', { orgId: params.org_id});
      }
    });

    // adapter
    export default ApplicationAdapter.extend(UrlTemplates, {
      queryUrlTemplate: '{+host}/{+namespace}/orgs/{orgId}/locations'
    });
    ```

    When I used this solution, it worked great but added the `orgId` as a Query String parameter to the end. I tried to debug where it was still getting added but haven't been able to find the root cause. 

You can consider this issue closed. Thanks again for the quick response! This add-on is great and going to help me considerably.

**Comment by amiel** [comment]
> I like the idea of injecting the context via a service. Any downsides you see to that?

Yeah, this is kind of where I was trying to go with the `session`. I've had a hard time recommending a specific way to deal with this because each case is so slightly different.

> I implemented your solution with query for a nested route that doesn't use any session data.

Looks good :)

> When I used this solution, it worked great but added the orgId as a Query String parameter to the end.

I have not experienced this. What version of ember-data are you using? I wonder if ember-data is appending your `orgId`. One troubleshooting step you could do is to implement the `orgId` urlSegment to delete its key, like this:

```javascript
// adapter
export default ApplicationAdapter.extend(UrlTemplates, {
  queryUrlTemplate: '{+host}/{+namespace}/orgs/{orgId}/locations',

  urlSegments: {
    orgId(type, id, snapshot, query) {
      var orgId = query.orgId;
      delete query.orgId;
      return orgId;
    },
  },
});
```

> This add-on is great and going to help me considerably.

I'm so glad to hear that; thank you!

**Comment by borwahs** [comment]
@amiel, thanks again! Overriding `orgId` and removing it from the `query` worked great. 

I am using Ember Data 2.3.3.
