### ISSUE TITLE
Update to match ED 1.13

### ISSUE THREAD

**Issue by knownasilya** [amiel/ember-data-url-templates#2]
So in ED 1.13 it's no longer `findQuery`, but `query` and `queryRecord`, and so on. Are there plans to update this addon to follow the new API?

**Comment by amiel** [comment]
I haven't upgraded to Ember Data 1.13 yet, but of course would like to support it.

Once I get around to upgrading the application I'm working on, I'll do this. If you need it before then, I would gladly accept a pull-request :D

**Comment by amiel** [comment]
@knownasilya I haven't been able to upgrade the application I'm working on to ED 1.13 yet, but I've been looking over the changes, and I don't think any updates to ember-data-url-templates are going to be necessary. Have you tried it or heard of any issues using ember-data-url-templates with ED 1.13?

**Comment by benoittgt** [comment]
Hello @amiel 
Thanks for the job done on ember-data-url-template. Do you have any update on this ? I'm on "ember-data": "1.13.8", and will probably downgrade to use ember-data-url-template.

**Comment by amiel** [comment]
@benoittgt I will do this when I get a chance to update a project I work on. This will definitely happen, but I'm not entirely sure when. My best guess is in 3-4 weeks, as I have some time slotted for maintenance after my current 3 week sprint.

**Comment by benoittgt** [comment]
@amiel it's ok. For the moment I'm trying to build my own 'restadapter' but that not the easiest to do when you starting ember. :)
Maybe [someone will do it](http://stackoverflow.com/questions/30793450/how-fetch-model-from-nested-resource-backend-in-emberjs/30817010?noredirect=1#comment52773208_30817010) before you.

**Comment by amiel** [comment]
@benoittgt: In case this helps, @bcardarella told me that [he is using ember-data-url-templates with ember-data 1.13](https://github.com/amiel/ember-data-url-templates/pull/5#issuecomment-128104435).

**Comment by benoittgt** [comment]
I finally made my own buildUrl like this

```javascript
export default DS.RESTAdapter.extend({
    host: 'http://www.exemple.com:3000',
    namespace: 'api/v1/',
    buildURL: function (modelName, id, snapshot, requestType, query) {
      var url = [];
      url.push(this.urlPrefix());
      url.push("users/" + query.user);
      delete query.user;
      url.push(this.pathForType(modelName));
      return url.join('/') + ".json";
    }
});
```

**Comment by drspaniel** [comment]
The url segment names are generated based on the method names, so no code changes are necessary to use `queryUrlTemplate` and `queryRecordUrlTemplate`.
See https://github.com/amiel/ember-data-url-templates/blob/master/addon/mixins/url-templates.js#L40

**Comment by knownasilya** [comment]
Thanks @drspaniel
