### ISSUE TITLE
Forward slash is being encoded

### ISSUE THREAD

**Issue by dzbo** [amiel/ember-data-url-templates#21]
I have namespace set to `api/v1` in my environment. After using template like 
```
urlTemplate: '{+host}{/namespace}/post/{postId}/comments'
``` 
I get following path `/api%2Fv1/post/1/comments` which unfortunately is not recognized properly in Mirage server.

My temporary solution is by doing `replace('%2F', '/')` in overrided `buildUrl` but would be great to have that in base code.

**Comment by amiel** [comment]
@dzbo would something like this work for you?

```javascript
namespace: 'api/v1',
urlTemplate: '{+host}/{+namespace}/post/{postId}/comments',
```

**Comment by dzbo** [comment]
@amiel yes! it works, so simple, thank you :)
