### ISSUE TITLE
namespace defined in ApplicationAdapter is not respected

### ISSUE THREAD

**Issue by rafaltrojanowski** [amiel/ember-data-url-templates#24]
In other words every adapter with UrlTemplates requires
direct definition of `namespace` within. Could you confirm?

**Comment by amiel** [comment]
Hi @rafaltrojanowski, I'm not sure I understand your question. Could you create an example that demonstrates the issue you are having?

**Comment by rafalt-iRonin** [comment]
Ah, adapters does work in a different way than I assumed. 
Defined rules (i.e. ```host```, ```namespace```) in ```adapter:application``` are superseded by model specific Adapters.

Please close this one :)

**Comment by rafaltrojanowski** [comment]
Ah, adapters work in a different way than I assumed.
Generally speaking, the rules defined in ```ApplicationAdapter``` are superseded by model specific Adapters.

Closing this one.
