### ISSUE TITLE
Adapter tests not returning proper URLs

### ISSUE THREAD

**Issue by Saldonas** [amiel/ember-data-url-templates#38]
I'm trying to fix some adapter unit tests I've written to make sure that the url generated for the route, in this case a query grabbing the current user, but the `urlForQueryRecord` isn't returning the correct URL, even when passing the correct options.

The route works just fine in my application, just not the tests. I'm not even doing anything fancy. Here's a look at the adapter:

```
  queryRecordUrlTemplate: '{+host}/{+namespace}/{pathForType}{/current}{/id}{?query*}',

  urlSegments: {
    current: function(type, id, snapshot, query) {
      if (query && query.current) {
        delete query.current;
        return 'current';
      }
    }
  }
```

and the test:
```
let adapter = this.subject(),
     urlForCurrentUser = adapter.urlForQueryRecord({ current: true }, 'users');
assert.equal(urlForCurrentUser, 'http://test/v1/users/current', 'the url hits the users/current endpoint');
```

but in the end it returns a URL without the `/current` at the end. I tried reaching out on the Slack ember-data channel but sadly didn't get any responses to what is probably a simple answer.

**Comment by amiel** [comment]
@Saldonas `ember-data-url-templates` overrides `buildURL` and doesn't actually use `urlForQueryRecord`.

Try this:

```js
// buildURL(type, id, snapshot, requestType, query)
let urlForCurrentUser = adapter.buildURL('user', null, null, 'queryRecord', { current: true });
```

**Comment by Saldonas** [comment]
@amiel Thank you so much!
