### ISSUE TITLE
Blog links in the Wiki are broken

### ISSUE THREAD

**Issue by belgoros** [amiel/ember-data-url-templates#41]
The following provided in Wiki links to blog articles are broken:

http://blog.ksol.fr/ember-data-working-with-nested-api-resources/
http://blog.ksol.fr/ember-data-working-with-custom-api-endpoints/

**Comment by amiel** [comment]
Hmmm, it looks like [the blogger](http://blog.ksol.fr/rewrite) has removed all of that previous content and switched subjects.

Thanks @belgoros, I will go ahead and remove those links.
