### ISSUE TITLE
findRecord(id) uses queryRecordUrlTemplate, not findRecordUrlTemplate

### ISSUE THREAD

**Issue by basz** [amiel/ember-data-url-templates#45]
with these definitions;

```
  urlTemplate: '{+host}/commerce/stores/{storeId}/catalogues/{catalogueId}/product-groups{/id}{?query*}',
  queryUrlTemplate: '{+host}/commerce/stores/{storeId}/catalogues/{catalogueId}/product-groups{/id}{?query*}',
  queryRecordUrlTemplate:
    '{+host}/commerce/stores/{storeId}/catalogues/{catalogueId}/product-group{?query*}',
  findRecordUrlTemplate: '{+host}/commerce/stores/{storeId}/catalogues/{catalogueId}/product-groups{/id}{?query*}',
```

If I do 
```
 .findRecord('commerce/product-group', productGroupId, {
        reload: true,
        include: 'parent.parent.parent.parent'
      })
```

The `queryRecordUrlTemplate` is used.

When I comment `queryRecordUrlTemplate` out `findRecordUrlTemplate` is used.

Am I doing this wrong? What logic is behind this?

**Comment by basz** [comment]
Could it be that queryTypes are changed from findRecord to queryRecord when there is a query object present? There is because of ember-data-slug that I'm using.

https://github.com/pangratz/ember-data-slug/blob/master/addon/mixins/adapter-slug-support.js

**Comment by basz** [comment]
Yes, confirmed, uninstalling data-slug resolved this issue. Now I need me slugs back somehow :-) thanks!

**Comment by amiel** [comment]
Good sleuthing @basz!

**Comment by basz** [comment]
Thanks, whats sleuthing? ;)

**Comment by amiel** [comment]
It’s like detective-work.
