### ISSUE TITLE
Ember 2.0 belongsTo snapshots don't return id of relationship target

### ISSUE THREAD

**Issue by jchamet** [amiel/ember-data-url-templates#7]

**Comment by jchamet** [comment]
I am closing this issue because the issue I was experiencing was fixed by making my custom adapters extend DS.JSONAPIAdapter instead of DS.RESTAdapter, which was fine before Ember Data 2.0

**Comment by amiel** [comment]
@jchamet Thanks for figuring this out.

It seems like most issues so far have been documentation issues. I plan to do some documentation updates soon, but would happily accept documentation PRs :)
