### ISSUE TITLE
Docs not comprehensive

### ISSUE THREAD

**Issue by drspaniel** [amiel/ember-data-url-templates#8]
`urlTemplate: '{+host}/posts/{postId}/comments{/id}',`
What does it mean to put the `+` or the leading `/` in the brackets?

What arguments are available to the urlSegments callbacks?

**Comment by amiel** [comment]
Yes. This is very true.

Until I (or someone else) gets to improving the documentation, here are a few answers:

`+` tells url templates not to escape the field (for example, without the `+`, a `host` might end up being `http%3A%2F%2Femberjs.com`)

A leading `/` inside the bracket includes the slash only if there is a value. For example:

```javascript
var template = new UrlTemplate("/comments/{/id}");
template.fillWithObject({ id: "1" }); // => "/comments/1";
template.fillWithObject({}); // => "/comments";
```

Full documentation on url-templates can be found here: https://tools.ietf.org/html/rfc6570

`urlSegments` get [these arguments](https://github.com/amiel/ember-data-url-templates/blob/master/addon/mixins/url-templates.js#L32): `(adapter, type, id, snapshot, query)`

**Comment by drspaniel** [comment]
As discussed in #4, we should mention escaping:
> But yes, I think it would be better if {+namespace} alongside {namespace: '/api'} was the default example.

**Comment by drspaniel** [comment]
> `urlSegments` get these arguments: `(adapter, type, id, snapshot, query)`

It is actually called with `adapter` as `this`, with arguments: `(type, id, snapshot, query)`

**Comment by drspaniel** [comment]
We should list the `*UrlTemplate` properties available, or mention that they automatically match up with all the `urlFor*` in [BuildURLMixin](http://emberjs.com/api/data/classes/DS.BuildURLMixin.html)

**Comment by amiel** [comment]
Thanks for thinking about this and gathering thoughts here!

**Comment by amiel** [comment]
Also, until I get a chance to dig in to the documentation further, there are two excellent blog posts that are far better at documenting what is possible than the README:

1. http://blog.ksol.fr/ember-data-working-with-custom-api-endpoints/
2. http://blog.ksol.fr/ember-data-working-with-nested-api-resources/

**Comment by amiel** [comment]
I'm starting to add some documentation in the wiki. In #11 I plan no slim down the README to just one example and mostly getting started information.

**Comment by drspaniel** [comment]
In this case I think you should definitely link to the wiki in the read me. I personally never check the wiki, and I've heard similar things from others

**Comment by amiel** [comment]
Definitely will do.

**Comment by amiel** [comment]
@drspaniel I've written some documentation in [the wiki](https://github.com/amiel/ember-data-url-templates/wiki) and included a link in [the README](https://github.com/amiel/ember-data-url-templates/blob/master/README.md#documentation).

There's still a few places where I've left myself TODOs as I didn't get to documenting everything mentioned here today. Please let me know if you have any feedback (also, feel free to make edits as you see fit).

**Comment by amiel** [comment]
@drspaniel ok, I think I've finished at least a good draft of each section. Would you close this if you think it's good enough for now; otherwise make some edits or let me know what you think needs changed.

**Comment by drspaniel** [comment]
:sparkles: Totally awesome and thorough :sparkles:
Thanks so much!
